### ISSUE TITLE
Animacións para victoria e derrota

### ISSUE THREAD

**Issue by SoniaPria** [Gommegab/Dxpp-2#15]
Na feature/gameManager o sprite de GameOver é provisional para que se vexa a funcionalidade. Póderíase mudar por outro máis a xeito co estilo do xogo.

**Comment by arieuger** [comment]
Creadas animacións de victoria e derrota, para o cal foi preciso importar o paquete URP e crear un shader para un efecto de desvanecemento. Engadidas tamén luces indicativas na meta e nos checkpoints e texto tutorial ao inicio da partida, que desaparece 3 segundos despois do primeiro movemento da cámara.

**Comment by SoniaPria** [comment]
#41 agrega efectos de audio ás dúas animacións.
