### ISSUE TITLE
Busca e importación de recursos de sonido

### ISSUE THREAD

**Issue by arieuger** [Gommegab/Dxpp-2#18]
Presisamos audio de fondo para, a lo menos, 3 situacións:  
  
- A escea inicial de primeiro contacto co xogo 
- As seguintes fases 
- O menú de Inicio/ Pausa.

**Comment by SoniaPria** [comment]
Este tema é libre de compartir e remezclar con atribución, e longo abondo para facer varios cortes en bucle.

https://commons.m.wikimedia.org/wiki/File:C418_-_circle_-_01_sleepless.flac

Podería valer, editado, para os 3 escenarios mencionados

**Comment by SoniaPria** [comment]
Enviado a revisión. Agrego + info na Wiki
