### ISSUE TITLE
Perder un corazón cando o personaxe cae

### ISSUE THREAD

**Issue by arieuger** [Gommegab/Dxpp-2#25]
En lugar de executar o _Game Over_, cada vez que o personaxe se caiga, perderase un corazón de vida e _respawnearase_ na mesma posición X na que se caeu.

**Comment by SoniaPria** [comment]
É verdade, cando a persoaxe cae por un foso execútase o _Game Over_ aínda tendo corazóns no seu haber: 



![Image](https://user-images.githubusercontent.com/122915931/228684117-8791c273-52a0-407b-93fe-1beee73ed1fc.png)

**Comment by SoniaPria** [comment]
Correxido na v0.2. 

A persoaxe ten un tempo limitado para chegar a meta e un crónómetro na GUI que indica o tempo restante. Se remata o tempo antes de chegares prodúcese o Game Over. 

O xogo comeza con 5 corazóns. Se a persoaxe cae nalgúns dos fosos da escea, perde un corazón e sitúase nun punto implementado antes dese foso que están pensados para que sexan ao principio da plataforma anterior ao foso para que a persoaxe vaia avanzando pese a caer. Cando perde tódolos corazaóns prodúcese o Game Over. 

Pulsando a tecla Escape aparece o Menú de Incio/Pausa e párase a partida. 
Se se pulsa a opción 'Reiniciar' comeza unha nova partida e restáunse o 5 corazóns. 
Se se pulsa a opción 'Continuar' a partida segue cos mesmos corazóns que antes de pausar.
