### ISSUE TITLE
Agregar collider al principio del nivel

### ISSUE THREAD

**Issue by SoniaPria** [Gommegab/Dxpp-2#30]
Cuando empiezas el juego te mueves hacia la izquierda te caes. Debería a ver un collider invisible al comienzo del escenario

**Comment by Gommegab** [comment]
es por cuestiones de jugabilidad no, tiene sentido que el jugador decida ir hacía la izquierda ya que si acaba de empezar no tenga claro a donde ir. por eso hay que bloquear que pueda caerse.
