### ISSUE TITLE
Cambiar velocidad del player

### ISSUE THREAD

**Issue by SoniaPria** [Gommegab/Dxpp-2#31]
La velocidad del player es muy baja parece que con 3.5 las animación queda mas creíble

**Comment by SoniaPria** [comment]
Tanto a velocidade como a forza de salto son variables públicas que se poden modificar no inspector:

![image](https://user-images.githubusercontent.com/122915931/228956120-b851f8f2-6999-4e9a-9b37-7bce921e14f5.png)

**Comment by Gommegab** [comment]
al ser publica es mejor que no se cambie en el start ya que si no siempre va a cambiar al valor del start y lo que le pongas en el Inspector no tiene ningun efecto
